[package]
name = "astrobwt"
version = "0.1.0"
authors = ["Slixe <slixeprivate@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.9.1"
salsa20 = "0.9.0"
byteorder = "1.1.0"